import * as mongoose from 'mongoose';

export const OrderSchema = new mongoose.Schema({
  field1: String,
  job_ref: String,
  cus_code: String,
  cus_ref: String,
  date: String,
  del_code: String,
  del_name: String,
  del_add1: String,
  del_add2: String,
  del_loc: String,
  del_state: String,
  del_post: String,
  del_country: String,
  depot: String,
  diary_ref: String,
  work_code: String,
  instructions: String,
  del_comment: String,
  del_ref: String,
  Ins_ref: String,
  value: String,
  drv_code: String,
  srv_code: String,
  cons_ref: String,
  col_code: String,
  lift: String,
  weight: String,
  cubic: String,
  class: String,
  phone: String,
  email: String,
  field2: String,
  prod_code: String,
  quantity: String,
  stk_grp: String,
  pallet_ref: String,
});
